---
- name: Setup Python Web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Install python and pip3
      yum:
        name: 
          - python3
          - python3-pip
        state: present
    
    - name: Install flask
      pip:
        name: flask
        executable: pip3
    
    - name: Create the flask app file
      copy:
        dest: /home/ec2-user/app.py
        content: |
          from flask import Flask, jsonify
          app = Flask(__name__)

          @app.route("/")
          def hello():
              return "Hello from Flask on {{ ansible_hostname }}!"
          
          @app.route("/health")
          def health():
              return jsonify({"status": "healthy"}), 200

          if __name__ == "__main__":
              app.run(host="0.0.0.0", port=8080)

    - name: Run the application
      shell: |
        nohup python3 /home/ec2-user/app.py > /home/ec2-user/app.log 2>&1 & disown
      args:
        chdir: /home/ec2-user
